apiVersion: v2
name: pricing
description: PAS pricing service (service catalog and price lists).
type: application
version: 0.1.0
appVersion: "main"
dependencies:
  - name: pas-common
    version: 0.1.0
    repository: "file://../../../infra/helm/pas-common"
