apiVersion: v2
name: esign-mock-provider
description: PAS esign-mock-provider service (mock e-signature provider (dev)).
type: application
version: 0.1.0
appVersion: "main"
dependencies:
  - name: pas-common
    version: 0.1.0
    repository: "file://../../../infra/helm/pas-common"
