import { mkdir, readFile, writeFile } from "node:fs/promises";
import openapiTS, { astToString } from "openapi-typescript";

const contractUrl = new URL("../../services/contract/src/main/resources/openapi.yaml", import.meta.url);
const outputUrl = new URL("../src/generated/contract-api.ts", import.meta.url);
const banner = `/**
 * Generated from services/contract/src/main/resources/openapi.yaml.
 * Do not edit this file directly; run \`bun run api:generate\`.
 */
`;

const generated = banner + astToString(await openapiTS(contractUrl));

if (process.argv.includes("--check")) {
  let current;
  try {
    current = await readFile(outputUrl, "utf8");
  } catch {
    current = "";
  }
  if (current !== generated) {
    console.error("Generated contract types are stale. Run `bun run api:generate` and commit the result.");
    process.exitCode = 1;
  }
} else {
  await mkdir(new URL("../src/generated/", import.meta.url), { recursive: true });
  await writeFile(outputUrl, generated);
  console.log("Generated src/generated/contract-api.ts");
}
