http:
  routers:
    identity-public:
      rule: PathPrefix(`/api/v1/auth`)
      entryPoints: [web]
      middlewares: [identity-ratelimit, api-v1-strip]
      service: identity
    identity:
      rule: PathPrefix(`/api/v1/users`) || PathPrefix(`/api/v1/roles`)
      entryPoints: [web]
      middlewares: [identity-ratelimit, jwt-auth@file, api-v1-strip]
      service: identity

  middlewares:
    identity-ratelimit:
      rateLimit:
        average: 100
        burst: 50
    api-v1-strip:
      stripPrefix:
        prefixes: [/api/v1]

  services:
    identity:
      loadBalancer:
        servers:
          - url: http://identity-service:8001
