apiVersion: v2
name: notification
description: PAS notification service (notifications).
type: application
version: 0.1.0
appVersion: "main"
dependencies:
  - name: pas-common
    version: 0.1.0
    repository: "file://../../../infra/helm/pas-common"
