/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdministrationRouteImport } from './routes/administration'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdministrationDocumentTypesRouteImport } from './routes/administration.document-types'
import { Route as AdministrationRolesRouteImport } from './routes/administration.roles'
import { Route as AdministrationUsersRouteImport } from './routes/administration.users'
import { Route as AdministrationWorkflowsRouteImport } from './routes/administration.workflows'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrationRoute = AdministrationRouteImport.update({
  id: '/administration',
  path: '/administration',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrationDocumentTypesRoute =
  AdministrationDocumentTypesRouteImport.update({
    id: '/document-types',
    path: '/document-types',
    getParentRoute: () => AdministrationRoute,
  } as any)
const AdministrationRolesRoute = AdministrationRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdministrationRoute,
} as any)
const AdministrationUsersRoute = AdministrationUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdministrationRoute,
} as any)
const AdministrationWorkflowsRoute = AdministrationWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => AdministrationRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/administration': typeof AdministrationRouteWithChildren
  '/login': typeof LoginRoute
  '/administration/document-types': typeof AdministrationDocumentTypesRoute
  '/administration/roles': typeof AdministrationRolesRoute
  '/administration/users': typeof AdministrationUsersRoute
  '/administration/workflows': typeof AdministrationWorkflowsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/administration': typeof AdministrationRouteWithChildren
  '/login': typeof LoginRoute
  '/administration/document-types': typeof AdministrationDocumentTypesRoute
  '/administration/roles': typeof AdministrationRolesRoute
  '/administration/users': typeof AdministrationUsersRoute
  '/administration/workflows': typeof AdministrationWorkflowsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/administration': typeof AdministrationRouteWithChildren
  '/login': typeof LoginRoute
  '/administration/document-types': typeof AdministrationDocumentTypesRoute
  '/administration/roles': typeof AdministrationRolesRoute
  '/administration/users': typeof AdministrationUsersRoute
  '/administration/workflows': typeof AdministrationWorkflowsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/administration'
    | '/login'
    | '/administration/document-types'
    | '/administration/roles'
    | '/administration/users'
    | '/administration/workflows'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/administration'
    | '/login'
    | '/administration/document-types'
    | '/administration/roles'
    | '/administration/users'
    | '/administration/workflows'
  id:
    | '__root__'
    | '/'
    | '/administration'
    | '/login'
    | '/administration/document-types'
    | '/administration/roles'
    | '/administration/users'
    | '/administration/workflows'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdministrationRoute: typeof AdministrationRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration': {
      id: '/administration'
      path: '/administration'
      fullPath: '/administration'
      preLoaderRoute: typeof AdministrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration/document-types': {
      id: '/administration/document-types'
      path: '/document-types'
      fullPath: '/administration/document-types'
      preLoaderRoute: typeof AdministrationDocumentTypesRouteImport
      parentRoute: typeof AdministrationRoute
    }
    '/administration/roles': {
      id: '/administration/roles'
      path: '/roles'
      fullPath: '/administration/roles'
      preLoaderRoute: typeof AdministrationRolesRouteImport
      parentRoute: typeof AdministrationRoute
    }
    '/administration/users': {
      id: '/administration/users'
      path: '/users'
      fullPath: '/administration/users'
      preLoaderRoute: typeof AdministrationUsersRouteImport
      parentRoute: typeof AdministrationRoute
    }
    '/administration/workflows': {
      id: '/administration/workflows'
      path: '/workflows'
      fullPath: '/administration/workflows'
      preLoaderRoute: typeof AdministrationWorkflowsRouteImport
      parentRoute: typeof AdministrationRoute
    }
  }
}

interface AdministrationRouteChildren {
  AdministrationDocumentTypesRoute: typeof AdministrationDocumentTypesRoute
  AdministrationRolesRoute: typeof AdministrationRolesRoute
  AdministrationUsersRoute: typeof AdministrationUsersRoute
  AdministrationWorkflowsRoute: typeof AdministrationWorkflowsRoute
}

const AdministrationRouteChildren: AdministrationRouteChildren = {
  AdministrationDocumentTypesRoute: AdministrationDocumentTypesRoute,
  AdministrationRolesRoute: AdministrationRolesRoute,
  AdministrationUsersRoute: AdministrationUsersRoute,
  AdministrationWorkflowsRoute: AdministrationWorkflowsRoute,
}

const AdministrationRouteWithChildren = AdministrationRoute._addFileChildren(
  AdministrationRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdministrationRoute: AdministrationRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
