/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AddendaRouteImport } from './routes/addenda'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AuditLogRouteImport } from './routes/audit-log'
import { Route as ContractsRouteImport } from './routes/contracts'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as ESignaturesRouteImport } from './routes/e-signatures'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PaymentStatementsRouteImport } from './routes/payment-statements'
import { Route as PriceListsRouteImport } from './routes/price-lists'
import { Route as VolumeRecordsRouteImport } from './routes/volume-records'
import { Route as AdminDocumentTypesRouteImport } from './routes/admin.document-types'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminWorkflowsRouteImport } from './routes/admin.workflows'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddendaRoute = AddendaRouteImport.update({
  id: '/addenda',
  path: '/addenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogRoute = AuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsRoute = ContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const ESignaturesRoute = ESignaturesRouteImport.update({
  id: '/e-signatures',
  path: '/e-signatures',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentStatementsRoute = PaymentStatementsRouteImport.update({
  id: '/payment-statements',
  path: '/payment-statements',
  getParentRoute: () => rootRouteImport,
} as any)
const PriceListsRoute = PriceListsRouteImport.update({
  id: '/price-lists',
  path: '/price-lists',
  getParentRoute: () => rootRouteImport,
} as any)
const VolumeRecordsRoute = VolumeRecordsRouteImport.update({
  id: '/volume-records',
  path: '/volume-records',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDocumentTypesRoute = AdminDocumentTypesRouteImport.update({
  id: '/document-types',
  path: '/document-types',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWorkflowsRoute = AdminWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/addenda': typeof AddendaRoute
  '/admin': typeof AdminRouteWithChildren
  '/approvals': typeof ApprovalsRoute
  '/audit-log': typeof AuditLogRoute
  '/contracts': typeof ContractsRoute
  '/customers': typeof CustomersRoute
  '/e-signatures': typeof ESignaturesRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/payment-statements': typeof PaymentStatementsRoute
  '/price-lists': typeof PriceListsRoute
  '/volume-records': typeof VolumeRecordsRoute
  '/admin/document-types': typeof AdminDocumentTypesRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/workflows': typeof AdminWorkflowsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/addenda': typeof AddendaRoute
  '/admin': typeof AdminRouteWithChildren
  '/approvals': typeof ApprovalsRoute
  '/audit-log': typeof AuditLogRoute
  '/contracts': typeof ContractsRoute
  '/customers': typeof CustomersRoute
  '/e-signatures': typeof ESignaturesRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/payment-statements': typeof PaymentStatementsRoute
  '/price-lists': typeof PriceListsRoute
  '/volume-records': typeof VolumeRecordsRoute
  '/admin/document-types': typeof AdminDocumentTypesRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/workflows': typeof AdminWorkflowsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/addenda': typeof AddendaRoute
  '/admin': typeof AdminRouteWithChildren
  '/approvals': typeof ApprovalsRoute
  '/audit-log': typeof AuditLogRoute
  '/contracts': typeof ContractsRoute
  '/customers': typeof CustomersRoute
  '/e-signatures': typeof ESignaturesRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/payment-statements': typeof PaymentStatementsRoute
  '/price-lists': typeof PriceListsRoute
  '/volume-records': typeof VolumeRecordsRoute
  '/admin/document-types': typeof AdminDocumentTypesRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/workflows': typeof AdminWorkflowsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/addenda'
    | '/admin'
    | '/approvals'
    | '/audit-log'
    | '/contracts'
    | '/customers'
    | '/e-signatures'
    | '/login'
    | '/notifications'
    | '/payment-statements'
    | '/price-lists'
    | '/volume-records'
    | '/admin/document-types'
    | '/admin/roles'
    | '/admin/users'
    | '/admin/workflows'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/addenda'
    | '/admin'
    | '/approvals'
    | '/audit-log'
    | '/contracts'
    | '/customers'
    | '/e-signatures'
    | '/login'
    | '/notifications'
    | '/payment-statements'
    | '/price-lists'
    | '/volume-records'
    | '/admin/document-types'
    | '/admin/roles'
    | '/admin/users'
    | '/admin/workflows'
  id:
    | '__root__'
    | '/'
    | '/addenda'
    | '/admin'
    | '/approvals'
    | '/audit-log'
    | '/contracts'
    | '/customers'
    | '/e-signatures'
    | '/login'
    | '/notifications'
    | '/payment-statements'
    | '/price-lists'
    | '/volume-records'
    | '/admin/document-types'
    | '/admin/roles'
    | '/admin/users'
    | '/admin/workflows'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddendaRoute: typeof AddendaRoute
  AdminRoute: typeof AdminRouteWithChildren
  ApprovalsRoute: typeof ApprovalsRoute
  AuditLogRoute: typeof AuditLogRoute
  ContractsRoute: typeof ContractsRoute
  CustomersRoute: typeof CustomersRoute
  ESignaturesRoute: typeof ESignaturesRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  PaymentStatementsRoute: typeof PaymentStatementsRoute
  PriceListsRoute: typeof PriceListsRoute
  VolumeRecordsRoute: typeof VolumeRecordsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/addenda': {
      id: '/addenda'
      path: '/addenda'
      fullPath: '/addenda'
      preLoaderRoute: typeof AddendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-log': {
      id: '/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuditLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts': {
      id: '/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof ContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e-signatures': {
      id: '/e-signatures'
      path: '/e-signatures'
      fullPath: '/e-signatures'
      preLoaderRoute: typeof ESignaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-statements': {
      id: '/payment-statements'
      path: '/payment-statements'
      fullPath: '/payment-statements'
      preLoaderRoute: typeof PaymentStatementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/price-lists': {
      id: '/price-lists'
      path: '/price-lists'
      fullPath: '/price-lists'
      preLoaderRoute: typeof PriceListsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volume-records': {
      id: '/volume-records'
      path: '/volume-records'
      fullPath: '/volume-records'
      preLoaderRoute: typeof VolumeRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/document-types': {
      id: '/admin/document-types'
      path: '/document-types'
      fullPath: '/admin/document-types'
      preLoaderRoute: typeof AdminDocumentTypesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/workflows': {
      id: '/admin/workflows'
      path: '/workflows'
      fullPath: '/admin/workflows'
      preLoaderRoute: typeof AdminWorkflowsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDocumentTypesRoute: typeof AdminDocumentTypesRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWorkflowsRoute: typeof AdminWorkflowsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDocumentTypesRoute: AdminDocumentTypesRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWorkflowsRoute: AdminWorkflowsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddendaRoute: AddendaRoute,
  AdminRoute: AdminRouteWithChildren,
  ApprovalsRoute: ApprovalsRoute,
  AuditLogRoute: AuditLogRoute,
  ContractsRoute: ContractsRoute,
  CustomersRoute: CustomersRoute,
  ESignaturesRoute: ESignaturesRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  PaymentStatementsRoute: PaymentStatementsRoute,
  PriceListsRoute: PriceListsRoute,
  VolumeRecordsRoute: VolumeRecordsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
